spring:
  application:    name: account-info-service
  
  datasource:    url: jdbc:h2:mem:testdb
  
  data:    jpa:      repositories:        bootstrap-mode: default
        
  jpa:    show-sql: true
    
  h2:    console:      enabled: true
   
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
        instance:
    prefer-ip-address: true
    
    